### ISSUE TITLE
Evolutions mapsquare

### ISSUE THREAD

**Issue by oduvoid** [takimafr/website#8]
Remplacer le bloc "OpenstreetMap" par le nouveau wording suivant.
Changer l'ordre des blocs en inversant les blocs DesignMyApp et OpenStreetMap. Mapsquare tools.

Nouveaux wording du bloc OpenStreetMap :

OpenStreetMap. Mapsquare tools.
OpenStreetMap (OSM) est une alternative open data à Google Maps, Bing et tant d'autres. eBiz apporte son expertise technique pour créer de nouveaux outils pour faciliter l'utilisation d'OSM par des entreprises.

Cette expertise et ces outils cartographiques sont aujourd'hui rassemblés dans l'offre mapsquare.io pour aider nos clients à prendre en main leurs outils cartographique de demain : serveurs de cartes personnalisées, app mobiles, intégration web.

mapsquare.io  (un clic sur ce lien ou sur le bloc fait afficher mapsquare.io)

Image à intégrer : 

![msquare_circle_500px](https://cloud.githubusercontent.com/assets/3639046/10580837/d099bdfa-767f-11e5-9196-ef5137789cca.png)

**Comment by loicortola** [comment]
Done
